server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/IAM
    username: postgres
    password: 123494
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    generate-ddl: true
  data:
    jpa:
      repositories:
        enabled: true
